spring:
  config:
    import:
      - 'classpath:adapter-http-property.yml'
      - 'classpath:adapter-persistence-property.yml'
      - 'classpath:adapter-redis-property.yml'
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ba3edfe43293cd2adedbe520f67c21f8
            client-secret: 2gtiHFgmY9C8YAvjRTtU6IqDoGRWPYQA
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:3000/login/oauth2/code/kakao"
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jwt:
    # openssl rand -hex 32
    secret: 1e9a9babf47c082fd065b03a9b916d476f8f901c7f7131201fb165100dc15135
    expire:
      access-token: 1
      refresh-token: 24